// Generated by dia2code
#ifndef STATE__EXEMPLE__H
#define STATE__EXEMPLE__H

#include <string>
#include <SFML/Graphics.hpp>

namespace state {

  /// class Exemple - 
  class Exemple {
    // Attributes
  public:
    int x     = 0;
    int y     = 0;
    std::string s;
    sf::Texture t;
    // Operations
  public:
    void setX (int x);
    // Setters and Getters
  };

};

#endif
