// Generated by dia2code
#ifndef STATE__RESMANAGER__H
#define STATE__RESMANAGER__H

#include <vector>
#include <memory>
#include <SFML/Graphics.hpp>
#include <string>

namespace state {

  /// class ResManager - 
  class ResManager {
    // Attributes
  public:
    std::shared_ptr<std::vector<sf::Texture>> textureCache     = nullptr;
  private:
    uint tileWidth     = 0;
    uint tileHeight     = 0;
    std::string tileSetPath     = "";
    uint tileSetColumns     = 0;
    std::string tilesetImageName     = "";
    uint tileCount     = 0;
    // Operations
  public:
    ResManager (std::string tileSetPath);
    bool init ();
    ~ResManager ();
    uint getTileCount ();
    uint getTileSetColumns ();
    uint getTileWidth ();
    uint getTileHeight ();
  private:
    bool pixelPicker (sf::Image image, uint tileIndex);
    // Setters and Getters
  };

};

#endif
