// Generated by dia2code
#ifndef __STATE__H
#define __STATE__H

#include "state/Layer.h"
#include "state/TileSet.h"
#include "state/Map.h"
#include "state/Position.h"
#include "state/Pokemon.h"
#include "state/Player.h"
#include "state/State.h"
#include "state/Salameche.h"
#include "state/Carapuce.h"
#include "state/Bulbizarre.h"
#endif
